lugares = ["Camp Nou", "Santiago Bernabéu", "Anfield", "San Siro", "Old Trafford"]
print(f"La lista original es {lugares}")
print(f"La lista ordenada alfabéticamente es {sorted(lugares)}")
print(f"La lista original sigue siendo {lugares}")
print(f"La lista ordenada alfabéticamente en orden inverso: {sorted(lugares, reverse=True)}")
print(f"La lista original sigue siendo {lugares}")
lugares.reverse()
print(f"La lista original ahora está en orden inverso: {lugares}")
lugares.reverse()
print(f"La lista original volvió a su orden original: {lugares}")
lugares.sort()
print(f"La lista original ahora está ordenada alfabéticamente: {lugares}")
lugares.sort(reverse=True)
print(f"La lista original ahora está ordenada alfabéticamente en orden inverso: {lugares}")